// Migración base para PostgreSQL: todas las tablas del modelo (docs/MODELO_DATOS.md).
// Reúne en una sola lo que en MySQL fueron las migraciones 0001 a 0007 (siguen en el historial de git).
// Reglas: las migraciones solo avanzan; nunca se edita una que ya corrió en producción, se agrega otra.
//
// Equivalencias con lo que hacía MySQL:
//   - utf8mb4_0900_ai_ci (sin distinguir mayúsculas ni acentos) → intercalación ICU `sin_acentos` en los
//     textos que se comparan con "=" o deben ser únicos (usuario, correo, nombres de catálogos).
//     Las búsquedas con LIKE usan f_unaccent(…) ILIKE (ver lib/buscar.ts).
//   - FULLTEXT → columna `busqueda` (tsvector) calculada sola, con índice GIN.
//   - ON UPDATE CURRENT_TIMESTAMP → disparador que actualiza `actualizado_at`.
//   - DATETIME(3) en UTC → TIMESTAMPTZ(3).  JSON → JSONB.  TINYINT(1) → BOOLEAN.
import { sql, type Kysely } from 'kysely';

const CREADO = 'creado_at TIMESTAMPTZ(3) NOT NULL DEFAULT now()';
const ACTUALIZADO = 'actualizado_at TIMESTAMPTZ(3) NOT NULL DEFAULT now()';
const ID_CHICO = 'id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
const ID = 'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
const ID_GRANDE = 'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
const TEXTO_SA = 'COLLATE sin_acentos';

const PREPARACION = [
  `CREATE EXTENSION IF NOT EXISTS unaccent`,
  // Nivel 1 de ICU: "José" = "jose" = "JOSE", como utf8mb4_0900_ai_ci.
  `CREATE COLLATION IF NOT EXISTS sin_acentos (provider = icu, locale = 'und-u-ks-level1', deterministic = false)`,
  // unaccent() no es IMMUTABLE (depende del diccionario configurado); esta versión fija el diccionario
  // y sí lo es, para poder usarla en la columna calculada de búsqueda y en índices.
  `CREATE OR REPLACE FUNCTION f_unaccent(text) RETURNS text
     LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
     AS $$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$`,
  `CREATE OR REPLACE FUNCTION fijar_actualizado_at() RETURNS trigger
     LANGUAGE plpgsql AS $$ BEGIN NEW.actualizado_at := now(); RETURN NEW; END $$`,
  `CREATE TYPE urgencia_ticket AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')`,
];

const TABLAS_SQL = [
  // ------------------------------------------------------------ acceso y permisos
  `CREATE TABLE roles (
    ${ID_CHICO},
    codigo VARCHAR(40) NOT NULL CONSTRAINT uq_roles_codigo UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    descripcion VARCHAR(255) NULL,
    es_sistema BOOLEAN NOT NULL DEFAULT FALSE,
    ${CREADO}, ${ACTUALIZADO}
  )`,

  `CREATE TABLE permisos (
    ${ID_CHICO},
    codigo VARCHAR(60) NOT NULL CONSTRAINT uq_permisos_codigo UNIQUE,
    grupo VARCHAR(40) NOT NULL,
    descripcion VARCHAR(255) NOT NULL
  )`,

  `CREATE TABLE rol_permisos (
    rol_id SMALLINT NOT NULL CONSTRAINT fk_rp_rol REFERENCES roles (id) ON DELETE CASCADE,
    permiso_id SMALLINT NOT NULL CONSTRAINT fk_rp_permiso REFERENCES permisos (id) ON DELETE CASCADE,
    PRIMARY KEY (rol_id, permiso_id)
  )`,
  `CREATE INDEX ix_rol_permisos_permiso ON rol_permisos (permiso_id)`,

  // ------------------------------------------------------------ catálogos
  `CREATE TABLE departamentos (
    ${ID_CHICO},
    nombre VARCHAR(80) ${TEXTO_SA} NOT NULL CONSTRAINT uq_departamentos_nombre UNIQUE,
    codigo VARCHAR(6) ${TEXTO_SA} NOT NULL CONSTRAINT uq_departamentos_codigo UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    orden SMALLINT NOT NULL DEFAULT 0,
    ${CREADO}, ${ACTUALIZADO}
  )`,

  `CREATE TABLE empresas (
    ${ID_CHICO},
    nombre VARCHAR(120) ${TEXTO_SA} NOT NULL CONSTRAINT uq_empresas_nombre UNIQUE,
    codigo VARCHAR(4) ${TEXTO_SA} NOT NULL CONSTRAINT uq_empresas_codigo UNIQUE,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    orden SMALLINT NOT NULL DEFAULT 0,
    ${CREADO}, ${ACTUALIZADO}
  )`,

  `CREATE TABLE tipos_solicitud (
    ${ID_CHICO},
    nombre VARCHAR(80) ${TEXTO_SA} NOT NULL CONSTRAINT uq_tipos_nombre UNIQUE,
    codigo VARCHAR(4) ${TEXTO_SA} NOT NULL CONSTRAINT uq_tipos_codigo UNIQUE,
    titulo_detalle VARCHAR(80) NOT NULL,
    requiere_modulo BOOLEAN NOT NULL DEFAULT TRUE,
    requiere_concepto BOOLEAN NOT NULL DEFAULT TRUE,
    requiere_folios BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    orden SMALLINT NOT NULL DEFAULT 0,
    ${CREADO}, ${ACTUALIZADO}
  )`,

  `CREATE TABLE modulos (
    ${ID_CHICO},
    nombre VARCHAR(80) ${TEXTO_SA} NOT NULL CONSTRAINT uq_modulos_nombre UNIQUE,
    codigo VARCHAR(6) ${TEXTO_SA} NULL CONSTRAINT uq_modulos_codigo UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    orden SMALLINT NOT NULL DEFAULT 0,
    ${CREADO}, ${ACTUALIZADO}
  )`,

  `CREATE TABLE estatus_ticket (
    codigo VARCHAR(20) NOT NULL PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL,
    clase_color VARCHAR(10) NOT NULL,
    es_final BOOLEAN NOT NULL DEFAULT FALSE,
    orden SMALLINT NOT NULL
  )`,

  // ------------------------------------------------------------ usuarios y sesiones
  `CREATE TABLE usuarios (
    ${ID},
    username VARCHAR(60) ${TEXTO_SA} NOT NULL CONSTRAINT uq_usuarios_username UNIQUE,
    nombre VARCHAR(120) ${TEXTO_SA} NULL,
    email VARCHAR(254) ${TEXTO_SA} NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol_id SMALLINT NOT NULL CONSTRAINT fk_usuarios_rol REFERENCES roles (id),
    departamento_id SMALLINT NULL CONSTRAINT fk_usuarios_departamento REFERENCES departamentos (id),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos SMALLINT NOT NULL DEFAULT 0,
    bloqueado_hasta TIMESTAMPTZ(3) NULL,
    ultimo_login_at TIMESTAMPTZ(3) NULL,
    password_cambiado_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    debe_cambiar_password BOOLEAN NOT NULL DEFAULT FALSE,
    eliminado_at TIMESTAMPTZ(3) NULL,
    origen VARCHAR(10) NOT NULL DEFAULT 'SISTEMA' CHECK (origen IN ('SISTEMA', 'IMPORTADO')),
    id_anterior INTEGER NULL,
    ${CREADO}, ${ACTUALIZADO},
    CONSTRAINT uq_usuarios_anterior UNIQUE (origen, id_anterior)
  )`,
  `CREATE INDEX ix_usuarios_rol ON usuarios (rol_id, eliminado_at)`,
  `CREATE INDEX ix_usuarios_email ON usuarios (email)`,

  `CREATE TABLE usuario_empresas (
    usuario_id INTEGER NOT NULL CONSTRAINT fk_ue_usuario REFERENCES usuarios (id) ON DELETE CASCADE,
    empresa_id SMALLINT NOT NULL CONSTRAINT fk_ue_empresa REFERENCES empresas (id),
    PRIMARY KEY (usuario_id, empresa_id)
  )`,
  `CREATE INDEX ix_ue_empresa ON usuario_empresas (empresa_id)`,

  `CREATE TABLE sesiones (
    id CHAR(64) NOT NULL PRIMARY KEY,
    usuario_id INTEGER NOT NULL CONSTRAINT fk_sesiones_usuario REFERENCES usuarios (id),
    csrf_token CHAR(64) NOT NULL,
    creada_at TIMESTAMPTZ(3) NOT NULL,
    ultima_actividad_at TIMESTAMPTZ(3) NOT NULL,
    expira_absoluta_at TIMESTAMPTZ(3) NOT NULL,
    cerrada_at TIMESTAMPTZ(3) NULL,
    motivo_cierre VARCHAR(12) NULL CHECK (motivo_cierre IN ('LOGOUT', 'INACTIVIDAD', 'EXPIRADA', 'ADMIN', 'BAJA', 'PASSWORD')),
    cerrada_por_id INTEGER NULL,
    ip VARCHAR(45) NOT NULL,
    user_agent VARCHAR(255) NOT NULL
  )`,
  `CREATE INDEX ix_sesiones_usuario ON sesiones (usuario_id, cerrada_at, ultima_actividad_at)`,
  `CREATE INDEX ix_sesiones_limpieza ON sesiones (cerrada_at, ultima_actividad_at)`,

  `CREATE TABLE intentos_login (
    ${ID_GRANDE},
    username VARCHAR(60) ${TEXTO_SA} NOT NULL,
    usuario_id INTEGER NULL,
    ip VARCHAR(45) NOT NULL,
    exito BOOLEAN NOT NULL,
    motivo VARCHAR(40) NULL,
    ${CREADO}
  )`,
  `CREATE INDEX ix_il_username ON intentos_login (username, creado_at)`,
  `CREATE INDEX ix_il_ip ON intentos_login (ip, creado_at)`,
  `CREATE INDEX ix_il_fecha ON intentos_login (creado_at)`,

  // ------------------------------------------------------------ tickets
  // Un registro por departamento + año; el consecutivo se reinicia en 0001 cada 1 de enero (tickets/folio.ts).
  `CREATE TABLE folio_contadores (
    departamento VARCHAR(6) NOT NULL,
    anio SMALLINT NOT NULL,
    ultimo_consecutivo INTEGER NOT NULL DEFAULT 0,
    ${ACTUALIZADO},
    PRIMARY KEY (departamento, anio)
  )`,

  `CREATE TABLE tickets (
    ${ID_GRANDE},
    folio VARCHAR(20) NOT NULL CONSTRAINT uq_tickets_folio UNIQUE,
    departamento_id SMALLINT NOT NULL CONSTRAINT fk_tickets_departamento REFERENCES departamentos (id),
    tipo_id SMALLINT NOT NULL CONSTRAINT fk_tickets_tipo REFERENCES tipos_solicitud (id),
    empresa_id SMALLINT NOT NULL CONSTRAINT fk_tickets_empresa REFERENCES empresas (id),
    modulo_id SMALLINT NULL CONSTRAINT fk_tickets_modulo REFERENCES modulos (id),
    concepto VARCHAR(200) NULL,
    folios_ref VARCHAR(500) NULL,
    descripcion_html TEXT NOT NULL,
    descripcion_texto TEXT NOT NULL,
    estatus VARCHAR(20) NOT NULL CONSTRAINT fk_tickets_estatus REFERENCES estatus_ticket (codigo),
    urgencia urgencia_ticket NOT NULL DEFAULT 'MEDIA',
    solicitante_id INTEGER NOT NULL CONSTRAINT fk_tickets_solicitante REFERENCES usuarios (id),
    creado_por_id INTEGER NOT NULL CONSTRAINT fk_tickets_creado_por REFERENCES usuarios (id),
    asignado_a_id INTEGER NULL CONSTRAINT fk_tickets_asignado REFERENCES usuarios (id),
    tomado_at TIMESTAMPTZ(3) NULL,
    primera_respuesta_at TIMESTAMPTZ(3) NULL,
    pausado_at TIMESTAMPTZ(3) NULL,
    cerrado_at TIMESTAMPTZ(3) NULL,
    cerrado_por_id INTEGER NULL CONSTRAINT fk_tickets_cerrado_por REFERENCES usuarios (id),
    version INTEGER NOT NULL DEFAULT 0,
    origen VARCHAR(10) NOT NULL DEFAULT 'SISTEMA' CHECK (origen IN ('SISTEMA', 'IMPORTADO')),
    id_anterior BIGINT NULL,
    ${CREADO}, ${ACTUALIZADO},
    -- Texto para la búsqueda libre: sin acentos y sin distinguir mayúsculas (diccionario "simple": no
    -- quita palabras comunes ni conjuga, igual que el FULLTEXT de MySQL). Todo lo que no sea letra o número
    -- se vuelve espacio, como al partir la búsqueda en tickets/consultas.ts: si no, "INV-1024" se leería
    -- como "inv" y el número negativo "-1024", y buscar "1024" no lo encontraría.
    busqueda TSVECTOR GENERATED ALWAYS AS (
      to_tsvector('simple', regexp_replace(
        f_unaccent(coalesce(concepto, '') || ' ' || coalesce(folios_ref, '') || ' ' || descripcion_texto),
        '[^[:alnum:]]+', ' ', 'g'
      ))
    ) STORED,
    CONSTRAINT uq_tickets_anterior UNIQUE (origen, id_anterior)
  )`,
  `CREATE INDEX ix_tickets_estatus ON tickets (estatus, creado_at)`,
  `CREATE INDEX ix_tickets_solicitante ON tickets (solicitante_id, estatus, creado_at)`,
  `CREATE INDEX ix_tickets_asignado ON tickets (asignado_a_id, estatus, creado_at)`,
  `CREATE INDEX ix_tickets_empresa ON tickets (empresa_id, creado_at)`,
  `CREATE INDEX ix_tickets_tipo ON tickets (tipo_id, creado_at)`,
  `CREATE INDEX ix_tickets_modulo ON tickets (modulo_id, creado_at)`,
  `CREATE INDEX ix_tickets_departamento ON tickets (departamento_id, creado_at)`,
  `CREATE INDEX ix_tickets_urgencia ON tickets (urgencia, estatus, creado_at)`,
  `CREATE INDEX ix_tickets_creado ON tickets (creado_at)`,
  `CREATE INDEX ft_tickets_texto ON tickets USING GIN (busqueda)`,

  `CREATE TABLE ticket_copias (
    ${ID_GRANDE},
    ticket_id BIGINT NOT NULL CONSTRAINT fk_copias_ticket REFERENCES tickets (id) ON DELETE CASCADE,
    usuario_id INTEGER NULL CONSTRAINT fk_copias_usuario REFERENCES usuarios (id),
    email VARCHAR(254) ${TEXTO_SA} NOT NULL,
    nombre VARCHAR(120) NULL,
    ${CREADO},
    CONSTRAINT uq_copias UNIQUE (ticket_id, email)
  )`,
  `CREATE INDEX ix_copias_usuario ON ticket_copias (usuario_id)`,

  `CREATE TABLE ticket_mensajes (
    ${ID_GRANDE},
    ticket_id BIGINT NOT NULL CONSTRAINT fk_mensajes_ticket REFERENCES tickets (id) ON DELETE CASCADE,
    autor_id INTEGER NOT NULL CONSTRAINT fk_mensajes_autor REFERENCES usuarios (id),
    tipo VARCHAR(12) NOT NULL CHECK (tipo IN ('COMENTARIO', 'RESPUESTA', 'RESOLUCION')),
    cuerpo_html TEXT NOT NULL,
    cuerpo_texto TEXT NOT NULL,
    ${CREADO}
  )`,
  `CREATE INDEX ix_mensajes_ticket ON ticket_mensajes (ticket_id, creado_at)`,

  `CREATE TABLE adjuntos (
    ${ID_GRANDE},
    uuid CHAR(36) NOT NULL CONSTRAINT uq_adjuntos_uuid UNIQUE,
    ticket_id BIGINT NULL CONSTRAINT fk_adjuntos_ticket REFERENCES tickets (id) ON DELETE CASCADE,
    mensaje_id BIGINT NULL CONSTRAINT fk_adjuntos_mensaje REFERENCES ticket_mensajes (id) ON DELETE CASCADE,
    subido_por_id INTEGER NOT NULL CONSTRAINT fk_adjuntos_usuario REFERENCES usuarios (id),
    nombre_original VARCHAR(255) NOT NULL,
    ruta_relativa VARCHAR(255) NOT NULL,
    mime VARCHAR(100) NOT NULL,
    tamano_bytes INTEGER NOT NULL,
    sha256 CHAR(64) NOT NULL,
    en_linea BOOLEAN NOT NULL DEFAULT FALSE,
    ${CREADO},
    eliminado_at TIMESTAMPTZ(3) NULL
  )`,
  `CREATE INDEX ix_adjuntos_ticket ON adjuntos (ticket_id, mensaje_id)`,
  `CREATE INDEX ix_adjuntos_temporales ON adjuntos (ticket_id, creado_at)`,

  `CREATE TABLE ticket_eventos (
    ${ID_GRANDE},
    ticket_id BIGINT NOT NULL CONSTRAINT fk_eventos_ticket REFERENCES tickets (id) ON DELETE CASCADE,
    actor_id INTEGER NULL CONSTRAINT fk_eventos_actor REFERENCES usuarios (id),
    tipo VARCHAR(40) NOT NULL,
    estatus_antes VARCHAR(20) NULL,
    estatus_despues VARCHAR(20) NULL,
    datos JSONB NULL,
    ${CREADO}
  )`,
  `CREATE INDEX ix_eventos_ticket ON ticket_eventos (ticket_id, creado_at)`,
  `CREATE INDEX ix_eventos_tipo ON ticket_eventos (tipo, creado_at)`,

  `CREATE TABLE notificaciones (
    ${ID_GRANDE},
    usuario_id INTEGER NOT NULL CONSTRAINT fk_notif_usuario REFERENCES usuarios (id) ON DELETE CASCADE,
    ticket_id BIGINT NOT NULL CONSTRAINT fk_notif_ticket REFERENCES tickets (id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('nuevo_ticket', 'ticket_contestado')),
    mensaje VARCHAR(255) NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    ${CREADO}
  )`,
  `CREATE INDEX ix_notif_usuario ON notificaciones (usuario_id, leida, creado_at)`,
  `CREATE INDEX ix_notif_limpieza ON notificaciones (leida, creado_at)`,

  // ------------------------------------------------------------ correo
  `CREATE TABLE plantillas_correo (
    ${ID_CHICO},
    codigo VARCHAR(40) NOT NULL CONSTRAINT uq_plantillas_codigo UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255) NULL,
    asunto VARCHAR(255) NOT NULL,
    cuerpo_html TEXT NOT NULL,
    variables JSONB NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    actualizado_por_id INTEGER NULL,
    ${ACTUALIZADO}
  )`,

  `CREATE TABLE correos_salida (
    ${ID_GRANDE},
    plantilla_codigo VARCHAR(40) NULL,
    ticket_id BIGINT NULL CONSTRAINT fk_correos_ticket REFERENCES tickets (id) ON DELETE SET NULL,
    para JSONB NOT NULL,
    cc JSONB NULL,
    asunto VARCHAR(255) NOT NULL,
    cuerpo_html TEXT NOT NULL,
    cuerpo_texto TEXT NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'ENVIANDO', 'ENVIADO', 'FALLIDO', 'CANCELADO')),
    intentos SMALLINT NOT NULL DEFAULT 0,
    max_intentos SMALLINT NOT NULL DEFAULT 7,
    proximo_intento_at TIMESTAMPTZ(3) NOT NULL,
    bloqueado_hasta TIMESTAMPTZ(3) NULL,
    ultimo_error VARCHAR(1000) NULL,
    transporte VARCHAR(20) NULL,
    id_mensaje_proveedor VARCHAR(255) NULL,
    ${CREADO},
    enviado_at TIMESTAMPTZ(3) NULL
  )`,
  `CREATE INDEX ix_correos_cola ON correos_salida (estado, proximo_intento_at)`,
  `CREATE INDEX ix_correos_ticket ON correos_salida (ticket_id)`,
  `CREATE INDEX ix_correos_fecha ON correos_salida (creado_at)`,

  // ------------------------------------------------------------ configuración y auditoría
  `CREATE TABLE ajustes (
    clave VARCHAR(60) NOT NULL PRIMARY KEY,
    valor JSONB NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    actualizado_por_id INTEGER NULL,
    ${ACTUALIZADO}
  )`,

  `CREATE TABLE auditoria (
    ${ID_GRANDE},
    actor_id INTEGER NULL,
    entidad VARCHAR(40) NOT NULL,
    entidad_id VARCHAR(40) NOT NULL,
    accion VARCHAR(40) NOT NULL,
    datos JSONB NULL,
    ip VARCHAR(45) NULL,
    ${CREADO}
  )`,
  `CREATE INDEX ix_auditoria_entidad ON auditoria (entidad, entidad_id, creado_at)`,
  `CREATE INDEX ix_auditoria_actor ON auditoria (actor_id, creado_at)`,
];

/** Tablas con `actualizado_at`: se actualiza solo en cada UPDATE (como ON UPDATE CURRENT_TIMESTAMP). */
const CON_ACTUALIZADO = [
  'roles',
  'departamentos',
  'empresas',
  'tipos_solicitud',
  'modulos',
  'usuarios',
  'folio_contadores',
  'tickets',
  'plantillas_correo',
  'ajustes',
];

const TABLAS = [
  'auditoria',
  'ajustes',
  'correos_salida',
  'plantillas_correo',
  'notificaciones',
  'ticket_eventos',
  'adjuntos',
  'ticket_mensajes',
  'ticket_copias',
  'tickets',
  'folio_contadores',
  'intentos_login',
  'sesiones',
  'usuario_empresas',
  'usuarios',
  'estatus_ticket',
  'modulos',
  'tipos_solicitud',
  'empresas',
  'departamentos',
  'rol_permisos',
  'permisos',
  'roles',
];

export async function up(db: Kysely<unknown>): Promise<void> {
  for (const s of [...PREPARACION, ...TABLAS_SQL]) await sql.raw(s).execute(db);
  for (const t of CON_ACTUALIZADO) {
    await sql.raw(`CREATE TRIGGER tr_${t}_actualizado BEFORE UPDATE ON ${t} FOR EACH ROW EXECUTE FUNCTION fijar_actualizado_at()`).execute(db);
  }
}

export async function down(db: Kysely<unknown>): Promise<void> {
  for (const t of TABLAS) await sql.raw(`DROP TABLE IF EXISTS ${t}`).execute(db);
  await sql`DROP TYPE IF EXISTS urgencia_ticket`.execute(db);
  await sql`DROP FUNCTION IF EXISTS fijar_actualizado_at()`.execute(db);
  await sql`DROP FUNCTION IF EXISTS f_unaccent(text)`.execute(db);
  await sql`DROP COLLATION IF EXISTS sin_acentos`.execute(db);
}
