// Respuestas guardadas: textos que cada técnico escribe una vez y luego inserta con un clic al responder.
// Son de cada usuario (nadie más las ve) y se borran con él.
import { sql, type Kysely } from 'kysely';

export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`CREATE TABLE respuestas_guardadas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL CONSTRAINT fk_respuestas_usuario REFERENCES usuarios (id) ON DELETE CASCADE,
    titulo VARCHAR(80) NOT NULL,
    cuerpo_html TEXT NOT NULL,
    creado_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    actualizado_at TIMESTAMPTZ(3) NOT NULL DEFAULT now()
  )`.execute(db);
  await sql`CREATE INDEX ix_respuestas_usuario ON respuestas_guardadas (usuario_id)`.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`DROP TABLE respuestas_guardadas`.execute(db);
}
