// Anuncios: avisos que los admins mandan como banner arriba de la pantalla, para todos o para ciertos
// departamentos. Se ven en cuanto se mandan y hasta que un admin los retira. Cada usuario puede cerrar
// los que no son urgentes (se recuerda en anuncio_cerrados, así no reaparecen en otra computadora).
import { sql, type Kysely } from 'kysely';

export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`CREATE TABLE anuncios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    tipo VARCHAR(12) NOT NULL CONSTRAINT ck_anuncios_tipo CHECK (tipo IN ('INFO', 'ADVERTENCIA', 'URGENTE')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_por_id INTEGER CONSTRAINT fk_anuncios_autor REFERENCES usuarios (id) ON DELETE SET NULL,
    creado_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    retirado_at TIMESTAMPTZ(3)
  )`.execute(db);
  await sql`CREATE INDEX ix_anuncios_activos ON anuncios (creado_at) WHERE activo`.execute(db);

  // Sin filas aquí = el anuncio es para todos.
  await sql`CREATE TABLE anuncio_departamentos (
    anuncio_id INTEGER NOT NULL CONSTRAINT fk_anuncio_dep_anuncio REFERENCES anuncios (id) ON DELETE CASCADE,
    departamento_id SMALLINT NOT NULL CONSTRAINT fk_anuncio_dep_departamento REFERENCES departamentos (id) ON DELETE CASCADE,
    PRIMARY KEY (anuncio_id, departamento_id)
  )`.execute(db);

  await sql`CREATE TABLE anuncio_cerrados (
    anuncio_id INTEGER NOT NULL CONSTRAINT fk_anuncio_cerrado_anuncio REFERENCES anuncios (id) ON DELETE CASCADE,
    usuario_id INTEGER NOT NULL CONSTRAINT fk_anuncio_cerrado_usuario REFERENCES usuarios (id) ON DELETE CASCADE,
    cerrado_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    PRIMARY KEY (anuncio_id, usuario_id)
  )`.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`DROP TABLE anuncio_cerrados`.execute(db);
  await sql`DROP TABLE anuncio_departamentos`.execute(db);
  await sql`DROP TABLE anuncios`.execute(db);
}
